name: 'Slack Share'
description: 'Share messages and file via this github action'
inputs:
  SLACK_TOKEN:  # id of input
    description: 'Slack Token'
    required: true
    default: 'No token'
  SHARE_FILE:  # id of input
    description: 'Share file boolean'
    required: false
    default: false
  SLACK_CHANNEL:  # id of input
    description: 'Slack channel'
    required: true
    default: 'general'
  FILE_PATH:  # id of input
    description: 'File path'
    required: false
    default: ''
  SLACK_MESSAGE:  # id of input
    description: 'Slack message'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'